<?php

use Illuminate\Database\Seeder;

class DomainTableSeeder extends Seeder {

    public function run() {
        // Uncomment the below to wipe the table clean before populating
        DB::table('grades')->delete();
        DB::table('abilities')->delete();
        DB::table('sexes')->delete();
        DB::table('leg_types')->delete();

        $grades = array(
            ['id' => 1, 
            'grade' => 'Open Level', 
            'description' => 'Three highest stats are below 65', 
            'created_at' => new DateTime, 
            'updated_at' => new DateTime],
            ['id' => 2, 
            'grade' => 'GIII', 
            'description' => '65 in any three or more stats',
            'created_at' => new DateTime, 
            'updated_at' => new DateTime],
            ['id' => 3, 
            'grade' => 'GII', 
            'description' => '75 in any two or more stats', 
            'created_at' => new DateTime, 
            'updated_at' => new DateTime],
            ['id' => 4, 
            'grade' => 'GI', 
            'description' => '85 in any one or more stats', 
            'created_at' => new DateTime, 
            'updated_at' => new DateTime]
            );

        $abilities = array(
            ['id' => 37, 'ability' => 'Bears', 
            'type' => 'negative', 
            'description' =>  'Bears right and left when stamina runs out', 
            'created_at' => new DateTime, 'updated_at' => new DateTime ],
            ['id' => 1, 'ability' => 'Best Course', 
            'type' => 'positive', 
            'description' =>  'Does better if it runs a course it likes', 
            'created_at' => new DateTime, 'updated_at' => new DateTime ],
            ['id' => 2, 'ability' => 'Close Race Not OK ', 'type' => 'negative', 
            'description' =>  'Performs poorly in close races', 
            'created_at' => new DateTime, 'updated_at' => new DateTime ],
            ['id' => 3, 'ability' => 'Close race OK', 'type' => 'positive', 
            'description' =>  'Excels in close races', 
            'created_at' => new DateTime, 'updated_at' => new DateTime ],
            ['id' => 4, 'ability' => 'Closer', 'type' => 'positive', 
            'description' =>  'races well when overtaking horses around the final corner', 
            'created_at' => new DateTime, 'updated_at' => new DateTime ],
            ['id' => 5, 'ability' => 'Delicate', 'type' => 'negative', 
            'description' =>  'Easily upset by bumping', 
            'created_at' => new DateTime, 'updated_at' => new DateTime ],
            ['id' => 6, 'ability' => 'Dust Not OK', 'type' => 'negative', 
            'description' =>  'Does not do well with dust', 
            'created_at' => new DateTime, 'updated_at' => new DateTime ],
            ['id' => 7, 'ability' => 'Fast Pace Not OK', 'type' => 'negative', 
            'description' =>  'races worse the faster the pace', 
            'created_at' => new DateTime, 'updated_at' => new DateTime ],
            ['id' => 8, 'ability' => 'Fast Pace OK', 'type' => 'positive', 
            'description' =>  'races better in faster paced races', 
            'created_at' => new DateTime, 'updated_at' => new DateTime ],
            ['id' => 9, 'ability' => 'Free', 'type' => 'positive', 
            'description' =>  'races well even when out of position', 
            'created_at' => new DateTime, 'updated_at' => new DateTime ],
            ['id' => 10, 'ability' => 'From Outside', 'type' => 'positive', 
            'description' =>  'Gives an impressive burst on the outside after staying towards the back during the race', 
            'created_at' => new DateTime, 'updated_at' => new DateTime ],
            ['id' => 11, 'ability' => 'Front Runner', 'type' => 'positive', 
            'description' =>  ' races well when leading the pack by a large margin. Only for front running horses', 
            'created_at' => new DateTime, 'updated_at' => new DateTime ],
            ['id' => 12, 'ability' => 'Grit', 'type' => 'positive', 
            'description' =>  'Excels going head-to-head with another horse to the finish line', 
            'created_at' => new DateTime, 'updated_at' => new DateTime ],
            ['id' => 13, 'ability' => 'Hates Pack', 'type' => 'negative', 
            'description' =>  'Upset when caught in a crowd', 
            'created_at' => new DateTime, 'updated_at' => new DateTime ],
            ['id' => 14, 'ability' => 'Inflexible', 'type' => 'negative', 
            'description' =>  'Cannot race out of position', 
            'created_at' => new DateTime, 'updated_at' => new DateTime ],
            ['id' => 15, 'ability' => 'Instant Response', 'type' => 'positive', 
            'description' =>  'Reacts quickly to the jockey', 
            'created_at' => new DateTime, 'updated_at' => new DateTime ],
            ['id' => 16, 'ability' => 'Last Corner Leader', 'type' => 'positive', 
            'description' =>  'Performs well after taking lead around the last corner', 
            'created_at' => new DateTime, 'updated_at' => new DateTime ],
            ['id' => 17, 'ability' => 'Last to First', 'type' => 'positive', 
            'description' =>  'Explodes in the stretch when trailing through the race', 
            'created_at' => new DateTime, 'updated_at' => new DateTime ],
            ['id' => 18, 'ability' => 'Likes Pack', 'type' => 'positive', 
            'description' =>  'Comfortable running in a pack', 
            'created_at' => new DateTime, 'updated_at' => new DateTime ],
            ['id' => 19, 'ability' => 'Loses Will', 'type' => 'negative', 
            'description' =>  'Easily distracted after taking lead around the last corner', 
            'created_at' => new DateTime, 'updated_at' => new DateTime ],
            ['id' => 20, 'ability' => 'Pace Down', 'type' => 'positive', 
            'description' =>  'Pace slower is okay', 
            'created_at' => new DateTime, 'updated_at' => new DateTime ],
            ['id' => 21, 'ability' => 'Pace Split', 'type' => 'positive', 
            'description' =>  'Okay if pack splits', 
            'created_at' => new DateTime, 'updated_at' => new DateTime ],
            ['id' => 22, 'ability' => 'Persistency', 'type' => 'positive', 
            'description' =>  'Keeps going', 
            'created_at' => new DateTime, 'updated_at' => new DateTime ],
            ['id' => 23, 'ability' => 'Rough Track Not OK', 'type' => 'negative', 
            'description' =>  'races poorly in rough track conditions', 
            'created_at' => new DateTime, 'updated_at' => new DateTime ],
            ['id' => 24, 'ability' => 'Rough Track OK', 'type' => 'positive', 
            'description' =>  'Performs well even in rough track conditions', 
            'created_at' => new DateTime, 'updated_at' => new DateTime ],
            ['id' => 25, 'ability' => 'Second Wind', 'type' => 'positive', 
            'description' =>  'When leading the pack all race long, further separates from the pack in the final stretch', 
            'created_at' => new DateTime, 'updated_at' => new DateTime ],
            ['id' => 26, 'ability' => 'Slow OK', 'type' => 'positive', 
            'description' =>  'races better in slower races', 
            'created_at' => new DateTime, 'updated_at' => new DateTime ],
            ['id' => 27, 'ability' => 'Slow Pace Not OK', 'type' => 'negative', 
            'description' =>  'races poorly in slower races', 
            'created_at' => new DateTime, 'updated_at' => new DateTime ],
            ['id' => 28, 'ability' => 'Slow Start', 'type' => 'negative', 
            'description' =>  'Slow at the beginning of the race', 
            'created_at' => new DateTime, 'updated_at' => new DateTime ],
            ['id' => 29, 'ability' => 'Solo Runner', 'type' => 'positive', 
            'description' =>  'Performs well when more than two lengths in the lead', 
            'created_at' => new DateTime, 'updated_at' => new DateTime ],
            ['id' => 30, 'ability' => 'Spurt', 'type' => 'positive', 
            'description' =>  'Excels when spurting from the back of the pack to ', 
            'created_at' => new DateTime, 'updated_at' => new DateTime ],
            ['id' => 31, 'ability' => 'Start Dash', 'type' => 'positive', 
            'description' =>  'Starts well at the beginning of the race', 
            'created_at' => new DateTime, 'updated_at' => new DateTime ],
            ['id' => 32, 'ability' => 'Stretch Burst', 'type' => 'positive', 
            'description' =>  'Shows a tremendous burst of speed to the finish line', 
            'created_at' => new DateTime, 'updated_at' => new DateTime ],
            ['id' => 33, 'ability' => 'Strong Heart', 'type' => 'positive', 
            'description' =>  'Whip gauge falls slower than other horses in the stretch if the horse still has stamina', 
            'created_at' => new DateTime, 'updated_at' => new DateTime ],
            ['id' => 34, 'ability' => 'Stubborn', 'type' => 'negative', 
            'description' =>  'Sprints uncontrollably when spooked', 
            'created_at' => new DateTime, 'updated_at' => new DateTime ],
            ['id' => 35, 'ability' => 'Tough', 'type' => 'positive', 
            'description' =>  'Unfazed by bumping', 
            'created_at' => new DateTime, 'updated_at' => new DateTime ],
            ['id' => 36, 'ability' => 'Whip', 'type' => 'positive', 
            'description' =>  'Accelerates faster than usual when whipped at the start of the race',
            'created_at' => new DateTime, 'updated_at' => new DateTime ]
            );

$sexes = array(
    ['id' => 1, 
    'sex' => 'Gelding', 
    'description' => 'Altered male horse', 
    'created_at' => new DateTime, 
    'updated_at' => new DateTime],
    ['id' => 2, 
    'sex' => 'Mare', 
    'description' => 'Unaltered female horse',
    'created_at' => new DateTime, 
    'updated_at' => new DateTime],
    ['id' => 3, 
    'sex' => 'Stallion', 
    'description' => 'Unaltered male horse', 
    'created_at' => new DateTime, 
    'updated_at' => new DateTime]
    );

$leg_type = array(
    ['id' => 1, 
    'type' => 'Closer', 
    'description' => 'This type of horse often drops to the back of the field and trails the field throughout the race, until it lets loose an explosive turn of foot. These horses will often look to be hopelessly beaten, then suddenly turn it on in the middle or deep stretch and charge down the track hellbent for the finish line. They can often overwhelm horses that ran near the pace and repel challenges from other closers.', 
    'created_at' => new DateTime, 
    'updated_at' => new DateTime],
    ['id' => 2, 
    'type' => 'Follower', 
    'description' => 'This type of horse is often found in the middle of the pack, happily running along and bumping into its fellows without a care in the world. They’re content to run five or more lengths off the leaders and make their moves near the middle of the stretch and can sometimes simply overwhelm a tiring leader or kick back a challenging closer. They are similar to closers, but run closer to the stalkers and leaders.', 
    'created_at' => new DateTime, 
    'updated_at' => new DateTime],
    ['id' => 3, 
    'type' => 'Front Runner', 
    'description' => 'This type of horse loves the lead and loves to run uncontested at the front of the pack. Often these horses hate the idea of other horses bumping or pushing them in the middle of the pack and will run away at the start to lead the rest of the field on a merry chase. These horses may or may not be able to hold off closers – more often they can fold under pressure. ', 
    'created_at' => new DateTime, 
    'updated_at' => new DateTime],
    ['id' => 4, 
    'type' => 'Stalker', 
    'description' => 'This type of horse is usually only a few lengths off the pace and tracking the leaders through each turn. These horses will bide their time then throw in a big move near the top or middle of a stretch, wearing down the leader to take over the top spot and hold on for the wire. Much like front runners, they may or may not be able to fend off the challengers of deep closers. ', 
    'created_at' => new DateTime, 
    'updated_at' => new DateTime]
    );

        // Uncomment the below to run the seeder
DB::table('grades')->insert($grades);
DB::table('abilities')->insert($abilities);
DB::table('sexes')->insert($sexes);
DB::table('leg_types')->insert($leg_type);
    }//end run

}
