<?php

use Illuminate\Database\Seeder;

class HorsesTableSeeder extends Seeder {

    public function run() {
        // Uncomment the below to wipe the table clean before populating
        DB::table('horses')->delete();
        

        DB::table('horses_progeny')->delete();

        $horses = array(

            ['id' => 1, 
            'owner' => 'Haubing', 
            'breeder' => 'Neco',
            'hexer' => 'Neco', 
            'call_name' => 'Riparian', 
            'registered_name' => 'Lessons Learned', 
            'sex' => 'Stallion', 
            'grade' => 'GI', 
            'leg_type' => 'Front Runner', 
            'color' => 'Black',
            'phenotype' => 'EE',
            'distance_min' => 8, 
            'distance_max' => 12, 
            'surface_dirt' => 'Good', 
            'surface_turf' => 'Good',
            'speed' => 87, 
            'staying' => 76, 
            'stamina' => 85, 
            'breaking' => 72, 
            'power' => 77, 
            'feel' => 71, 
            'fierce' => 71, 
            'tenacity' => 71, 
            'courage' => 75, 
            'response' => 77,   
            'pos_ability_1' => 'Front Runner', 
            'pos_ability_2' => 'Second Wind', 
            'neg_ability_1' => 'Stubborn',  
            'neck_height' => 'Normal', 
            'run_style' => 'Normal', 
            'bandages' => 'Both', 
            'hood' => 'Yes', 
            'shadow_roll' => 'Yes',       
            'stall_path' => '/stall/1',
            'img_path' => 'http://leahmhb.info/stall_img/Riparian.png',
            'created_at' => new DateTime, 
            'updated_at' => new DateTime],

            ['id' => 2, 
            'owner' => 'Haubing', 
            'hexer' => 'Katann', 
            'breeder' => '',
            'call_name' => 'American Pharoah', 
            'registered_name' => 'Divine Right', 
            'sex' => 'Stallion', 
            'grade' => 'GIII', 
            'leg_type' => 'Front Runner', 
            'color' => 'Bay',
            'phenotype' => 'EeAa',
            'distance_min' => 8, 
            'distance_max' => 12, 
            'surface_dirt' => 'Great', 
            'surface_turf' => 'Okay',
            'speed' => 87, 
            'staying' => 69, 
            'stamina' => 69, 
            'breaking' => 68, 
            'power' => 69, 
            'feel' => 69, 
            'fierce' => 67, 
            'tenacity' => 68, 
            'courage' => 67, 
            'response' => 68,    
            'pos_ability_1' => 'Last Corner Leader', 
            'pos_ability_2' => 'Second Wind', 
            'neg_ability_1' => 'Dust Not OK', 
            'neck_height' => 'Normal', 
            'run_style' => 'Normal', 
            'bandages' => 'Both', 
            'hood' => 'No', 
            'shadow_roll' => 'Yes',      
            'stall_path' => '/stall/2',
            'img_path' => 'http://leahmhb.info/stall_img/American%20Pharoah.png',        
            'created_at' => new DateTime, 
            'updated_at' => new DateTime],

            ['id' => 3, 
            'owner' => 'Haubing', 
            'hexer' => 'Neco', 
            'breeder' => 'Neco',
            'call_name' => 'Sovenance', 
            'registered_name' => 'A Kinder Reminiscence', 
            'sex' => 'Mare', 
            'grade' => 'GII', 
            'leg_type' => 'Closer', 
            'color' => 'Bay',
            'phenotype' => 'EeAA',
            'distance_min' => 8, 
            'distance_max' => 12, 
            'surface_dirt' => 'Great', 
            'surface_turf' => 'Okay', 
            'speed' => 76, 
            'staying' => 71, 
            'stamina' => 80, 
            'breaking' => 70, 
            'power' => 72, 
            'feel' => 67, 
            'fierce' => 73, 
            'tenacity' => 63, 
            'courage' => 65, 
            'response' => 73,    
            'pos_ability_1' => 'Stretch Burst', 
            'pos_ability_2' => 'Closer', 
            'neg_ability_1' => 'Slow Start', 
            'neck_height' => 'Normal', 
            'run_style' => 'Normal', 
            'bandages' => 'Both', 
            'hood' => 'No', 
            'shadow_roll' => 'Yes',   
            'stall_path' => '/stall/3',
            'img_path' => 'http://leahmhb.info/stall_img/Sovenance.png',         
            'created_at' => new DateTime, 
            'updated_at' => new DateTime],

            ['id' => 4, 
            'owner' => 'Haubing', 
            'hexer' => 'Artemis', 
            'breeder' => 'Artemis',
            'call_name' => 'Trickery', 
            'registered_name' => 'Beneath Still Waters', 
            'sex' => 'Stallion', 
            'grade' => 'Open Level', 
            'leg_type' => 'Closer', 
            'color' => 'Bay',
            'phenotype' => 'EeAA',
            'distance_min' => 7, 
            'distance_max' => 10, 
            'surface_dirt' => 'Good', 
            'surface_turf' => 'Good', 
            'speed' => 67, 
            'staying' => 70, 
            'stamina' => 70, 
            'breaking' => 60, 
            'power' => 60, 
            'feel' => 61, 
            'fierce' => 62, 
            'tenacity' => 60, 
            'courage' => 58, 
            'response' => 58,    
            'pos_ability_1' => 'Stretch Burst', 
            'pos_ability_2' => 'Instant Response', 
            'neg_ability_1' => 'Stubborn', 
            'neck_height' => 'Normal', 
            'run_style' => 'Normal', 
            'bandages' => 'Both', 
            'hood' => 'No', 
            'shadow_roll' => 'Yes',    
            'stall_path' => '/stall/4',
            'img_path' => 'http://leahmhb.info/stall_img/Trickery.png',        
            'created_at' => new DateTime, 
            'updated_at' => new DateTime]
            );


        // Uncomment the below to run the seeder
    DB::table('horses')->insert($horses);
    }//end run

}
